collections:
  posts:
    output: true
  eventos:
    output: true
  blog:
    output: true

defaults:
  - scope:
      path: ""
      type: "eventos"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "blog"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "default"
  - scope:
      path: ""
    values:
      layout: "default"